<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoSeed.Core\AutoSeed.Core.csproj" />
    <ProjectReference Include="..\..\src\AutoSeed.Inference\AutoSeed.Inference.csproj" />
    <ProjectReference Include="..\..\src\AutoSeed.Providers\AutoSeed.Providers.csproj" />
  </ItemGroup>

</Project>
