<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>EFCore.AutoSeed.Inference</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoSeed.Core\AutoSeed.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
  </ItemGroup>

</Project>
