namespace EFCore.AutoSeed.Exceptions;

/// <summary>
/// Thrown when a required (non-nullable) property is not generated by the database and cannot be
/// given a value, whether because no inference rule recognizes it or because its custom generator
/// returned <see langword="null"/> for a row, so it would otherwise reach the database at its CLR
/// default, most often violating a <c>NOT NULL</c> constraint.
/// </summary>
public sealed class UnsupportedPropertyException : AutoSeedException
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UnsupportedPropertyException"/> class.
    /// </summary>
    /// <param name="entityTypeName">The full name of the entity type that owns the property.</param>
    /// <param name="propertyName">The name of the property that could not be given a value.</param>
    /// <param name="reason">Why <paramref name="propertyName"/> could not be given a value.</param>
    public UnsupportedPropertyException(string entityTypeName, string propertyName, string reason)
        : base(BuildMessage(entityTypeName, propertyName, reason))
    {
        EntityTypeName = entityTypeName;
        PropertyName = propertyName;
    }

    /// <summary>
    /// The full name of the entity type that owns the property.
    /// </summary>
    public string EntityTypeName { get; }

    /// <summary>
    /// The name of the property that could not be given a value.
    /// </summary>
    public string PropertyName { get; }

    private static string BuildMessage(string entityTypeName, string propertyName, string reason) =>
        $"Cannot seed {entityTypeName}.{propertyName}: it is required, not generated by the database, and {reason}.";
}
