namespace EFCore.AutoSeed.Exceptions;

/// <summary>
/// Thrown when a required (non-nullable) property is not generated by the database and no
/// inference rule recognizes it, so it would otherwise reach the database at its CLR default,
/// most often violating a <c>NOT NULL</c> constraint.
/// </summary>
public sealed class UnsupportedPropertyException : AutoSeedException
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UnsupportedPropertyException"/> class.
    /// </summary>
    /// <param name="entityTypeName">The full name of the entity type that owns the property.</param>
    /// <param name="propertyName">The name of the property no rule could infer a value for.</param>
    /// <param name="clrTypeName">The property's CLR type name.</param>
    public UnsupportedPropertyException(string entityTypeName, string propertyName, string clrTypeName)
        : base(BuildMessage(entityTypeName, propertyName, clrTypeName))
    {
        EntityTypeName = entityTypeName;
        PropertyName = propertyName;
    }

    /// <summary>
    /// The full name of the entity type that owns the property.
    /// </summary>
    public string EntityTypeName { get; }

    /// <summary>
    /// The name of the property no rule could infer a value for.
    /// </summary>
    public string PropertyName { get; }

    private static string BuildMessage(string entityTypeName, string propertyName, string clrTypeName) =>
        $"Cannot seed {entityTypeName}.{propertyName}: it is required, not generated by the database, and no inference " +
        $"rule recognizes its type ({clrTypeName}). Open an issue describing the property's shape.";
}
